---
cVMs:
- name: hello
  disk: disk_docker.img
  runtime: libmusl-lkl.so
  args: "/ld.so /usr/bin/redis-server /redis.conf"
  isolation:
  - base: 0x20000000
    size: 0x10000000
    begin: 0x20000000
    end: 0x30000000